spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: lemoon.can.milkyway.infrastructure.repository.dos
  type-handlers-package: lemoon.can.milkyway.infrastructure.repository.mapper.type
  configuration:
    map-underscore-to-camel-case: true