jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-validity: 2592000000   # 30天

security:
  permit-urls:
    - /auth/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - /error
  get-permit-urls:
    - /files/**
  secure-id:
    friend-application-salt: ${FRIEND_APPLICATION_SECUREID_SALT}
    chat-salt: ${CHAT_SECUREID_SALT}
    message-salt: ${MESSAGE_SECUREID_SALT}
    moment-salt: ${MOMENT_SECUREID_SALT}
    comment-salt: ${COMMENT_SECUREID_SALT}

file:
  access:
    secret-key: ${FILE_ACCESS_SECRET_KEY}