spring:
  application:
    name: milky-way
  profiles:
    include: datasource,security,openapi

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG
    lemoon:
      messageboard: DEBUG

env:
  domain: https://localhost:8081/
  fileAccessUrl: files/


