#https证书配置
server:
    ssl:
        key-store: ${SSL_KEY_STORE}
        key-store-password: ${SSL_KEY_PASSWORD}
        key-password: ${SSL_KEY_PASSWORD}
        key-store-type: ${SSL_KEY_STORE_TYPE}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-validity: 2592000000   # 30天

security:
  permit-urls:
    - /auth/**
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - /error
  cors:
    allowed-origins: #此类-分隔的配置，只能被@ConfigurationProperties方式解析
      - http://localhost:3000
      - chrome-extension://cbcbkhdmedgianpaifchdaddpnmgnknn
  secure-id:
    friend-application-salt: ${FRIEND_APPLICATION_SECUREID_SALT}
    chat-salt: ${CHAT_SECUREID_SALT}
    message-salt: ${MESSAGE_SECUREID_SALT}
    moment-salt: ${MOMENT_SECUREID_SALT}
    comment-salt: ${COMMENT_SECUREID_SALT}
  websocket:
    cors-allowed-origins:
       - http://localhost:8081
       - chrome-extension://cbcbkhdmedgianpaifchdaddpnmgnknn

file:
  access:
    secret-key: sun