logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        web: TRACE
        org.springframework.messaging: TRACE
        org.springframework.messaging.simp: TRACE


    lemoon:
      can:
        milkyway: DEBUG

