logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
        web: TRACE
        org.springframework.messaging: TRACE
        org.springframework.messaging.simp: TRACE
        org.springframework.messaging.simp.broker: TRACE
        org.springframework.messaging.simp.user: TRACE

    lemoon:
      can:
        milkyway: DEBUG

